[base]
map='m'          #地图
interaction='f'  #互动
swoop='q'        #凤凰俯冲
read="success!"


[time]
waittime=15        #执行一大轮之后tabo后的等待时间 默认为15
waittime_after_run=0.7 #每次开图时按M后等待时间 默认为0.7
faliuretime1=15     #长按着陆点后等待落地时间 默认15
faliuretime2=20    #进图后等待时间 默认20
swordtime=2        #刀重击后等待时间 根据刀不同框架的后摇调整

[run]
circulate=15       #循环次数 即一大轮要执行多少小轮 默认15
movetimes=20
movepx=50   #控制开图时鼠标移动到最左边后往右移的位移量 movetimes移动次数 movepx代表每次移动像素 默认为(20,50) 有问题请尝试(20,40)
thelastchest=1580  #最后一箱的跑步距离 默认1580
landingx=1498
landingy=913 #从轨道进图点开始位置

[switch]
warlock=false          #是否开启术士地狱火版本 开启为true 关闭为false
sword=true            #是否开启故我在挥刀
Ammo=true             #是否开启无绿弹自动切换重弹
landingerror=true    #是否开启检测进图是否成功